spring:
  config:
    activate:
      on-profile: dev

  devtools:
    add-properties: true

  # C?u h?nh JPA, Hibernate m?c ??nh.
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
#    config-url: true
openapi:
  service:
    api-docs: backend-service
    title: Backend API Documentation
    version: v1.0.0
    server: http://localhost:8080

jwt:
  secretKey: jwt.secretKey.dev